import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import  Navbar  from "@/components/layout/Navbar";
import  Footer  from "@/components/layout/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
         <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
    <Navbar />
    <main className="pt-16 pb-16">
      <div className="mx-auto">
        {children}
      </div>
    </main>
    <Footer />
  </div>
      </body>
    </html>
  );
}
